name: iOS Snyk Vulnerability Scan

on:
  push:
    branches: [ main ]

jobs:
  snyk:
    name: Run Snyk on Podfile.lock
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Install Pods
        run: pod install

      - name: Run Snyk to test for vulnerabilities
        run: snyk test --file=Podfile.lock --severity-threshold=low | tee snyk-report.txt
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true

      - name: Upload Snyk Vulnerability Report
        uses: actions/upload-artifact@v4
        with:
          name: snyk-vulnerability-report
          path: snyk-report.txt
