name: iOS Code Review

on:
  push:
    branches: [ main ]

jobs:
  lint:
    name: SwiftLint and SwiftFormat
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint (only errors)
        run: swiftlint --quiet --reporter xcode --strict | tee swiftlint-errors.txt
        continue-on-error: true

      - name: Install SwiftFormat
        run: brew install swiftformat

      - name: Run SwiftFormat Check
        run: swiftformat . --lint
        continue-on-error: true

      - name: Generate SwiftLint JSON Report
        if: always()
        run: |
          swiftlint --reporter json > swiftlint-report.json || true

      - name: Upload SwiftLint Error Log
        uses: actions/upload-artifact@v4
        with:
          name: swiftlint-errors
          path: swiftlint-errors.txt

      - name: Upload Full SwiftLint JSON Report
        uses: actions/upload-artifact@v4
        with:
          name: swiftlint-report
          path: swiftlint-report.json

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Install iOS Dependencies (Pod Install)
        run: pod install

      - name: Snyk Test (Podfile.lock)
        uses: snyk/actions@master
        with:
          command: test
          file: Podfile.lock
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }} 
