name: iOS Build CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Ruby, CocoaPods, and xcpretty
      run: |
        ruby_version="3.2"
        cocoapods_version="1.16.2"

        # Install Ruby
        brew install ruby@$ruby_version || exit 1
        export PATH="/opt/homebrew/opt/ruby@$ruby_version/bin:$PATH"

        # Install CocoaPods
        sudo gem install cocoapods -v $cocoapods_version || exit 1

        # Install xcpretty
        sudo gem install xcpretty || exit 1

        # Verify installations
        ruby -v
        cocoapods --version
        xcodebuild -version
      shell: bash

    - name: Install CocoaPods dependencies
      run: pod install
      working-directory: ./  # Adjust if necessary

    - name: Set Xcode version
      run: |
        xcode_version="16.2"
        sudo xcode-select --switch /Applications/Xcode-$xcode_version.app || exit 1
        xcodebuild -version

    - name: Build project
      run: |
        xcodebuild -workspace Woloo.xcworkspace -scheme Woloo -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 13' build

    - name: Run unit tests
      run: |
        xcodebuild -workspace Woloo.xcworkspace -scheme Woloo -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 13' test | \
          tee result.log | xcpretty -r junit
      continue-on-error: true

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: junit-report
        path: result.log
