name: iOS Build CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Ruby 3.2, CocoaPods 1.16.2, xcpretty, and Xcode 16.2
      run: |
        ruby_version="3.2"  # Use ruby 3.2, as 3.3.3 isn't available
        cocoapods_version="1.16.2"
        xcode_version="16.2"

        # Install Ruby 3.2 (closest available version)
        brew install ruby@$ruby_version && \
        
        # Install CocoaPods with the specific version
        sudo gem install cocoapods -v $cocoapods_version && \
        
        # Install xcpretty
        sudo gem install xcpretty && \
        
        # Install xcodes (to manage Xcode versions)
        brew install --cask xcodes && \
        
        # Install Xcode 16.2 using xcodes
        xcversion install $xcode_version && \
        
        # Set Xcode 16.2 as the active version
        sudo xcode-select --switch /Applications/Xcode-$xcode_version.app && \
        
        # Verify Xcode version
        xcodebuild -version && \
        xcode-select -p
      shell: bash

    - name: Install CocoaPods dependencies
      run: |
        pod install
      working-directory: ./  # Assuming the Podfile is in the root directory

    - name: Build project
      run: |
        xcodebuild -workspace Woloo.xcworkspace -scheme Woloo -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13' build

    - name: Run unit tests (when test cases are available)
      run: |
        xcodebuild -workspace Woloo.xcworkspace -scheme Woloo -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13' test | tee result.log | xcpretty -r junit
      continue-on-error: true

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: junit-report
        path: result.xml
