name: iOS CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List all Xcode versions
        run: |
          ls /Applications | grep Xcode

      - name: Set up Xcode 14.2 (adjust the path based on the listing)
        run: |
          sudo xcode-select --switch /Applications/Xcode_14.2.app

      - name: Install Ruby and CocoaPods
        run: |
          ruby -v
          sudo gem install cocoapods -v 1.16.2
          
      - name: Install dependencies with CocoaPods
        run: |
          pod install --repo-update

      - name: Build the project
        run: |
          xcodebuild clean build -workspace YourWorkspace.xcworkspace -scheme YourScheme -sdk iphoneos
