name: iOS Build CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set Xcode version
      run: |
        xcode_version="15.0.1" # Use the exact available version
        sudo xcode-select --switch /Applications/Xcode_$xcode_version.app || exit 1
        xcodebuild -version



    - name: Install Ruby, CocoaPods, and xcpretty
      run: |
        ruby_version="3.2"
        cocoapods_version="1.16.2"
        # Install Ruby
        brew install ruby@$ruby_version || exit 1
        export PATH="/opt/homebrew/opt/ruby@$ruby_version/bin:$PATH"
        # Install CocoaPods
        gem install cocoapods -v $cocoapods_version || exit 1
        # Install xcpretty
        gem install xcpretty || exit 1
        # Veri
