name: iOS CI/CD Workflow

on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    name: iOS Build and Test
    runs-on: macos-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Select Xcode version
      - name: Select Xcode Version
        run: sudo xcode-select -switch /Applications/Xcode_16.2.app

      # Step 3: Verify Xcode version
      - name: Verify Xcode Version
        run: xcodebuild -version

      # Step 4: Clean Build Directory
      - name: Clean Build Directory
        run: |
          xcodebuild clean -project Woloo.xcodeproj -scheme Woloo | xcpretty

      # Step 5: Build Project
      - name: Build Project
        run: |
          xcodebuild build -project Woloo.xcodeproj -scheme Woloo -destination 'platform=iOS Simulator' | xcpretty
          
      # Step 6: Run Test Cases and Save Results
      - name: Run Tests and Save Results
        run: |
          mkdir -p ios-test-results
          xcodebuild test -project Woloo.xcodeproj -scheme Woloo -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.2' | xcpretty | tee ios-test-results/results.txt

      # Step 7: Upload Test Results
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ios-test-results
          path: ios-test-results/results.txt
