name: GitHub Action 

on: 
  push:
    branches:    
      - master
      
jobs:
  deploy:
    name: GitHub Pipeline
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Selecting Xcode Version
        run: sudo xcode-select -switch /Applications/Xcode_16.2.app
        
      - name: Running Xcode version Is?
        run: /usr/bin/xcodebuild -version
       
      - name: Build Cleanup
        run: |
          xcodebuild clean -project Woloo.xcodeproj -scheme Woloo | xcpretty
          
      - name: Build Test
        run: |
          xcodebuild test -project Woloo.xcodeproj -scheme Woloo -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.2' -resultBundle -reporter junit | xcpretty -s
          
      - name: Save Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: ./TestResults/*.xml  # Path to the JUnit XML report
          
      - name: Parse Test Results Summary
        run: |
          if [ -f ./TestResults/Test-*.xml ]; then
            tests_failed=$(xmllint --xpath "count(//testcase[failure])" ./TestResults/Test-*.xml)
            tests_total=$(xmllint --xpath "count(//testcase)" ./TestResults/Test-*.xml)
            tests_passed=$((tests_total - tests_failed))
            echo "Tests Passed: $tests_passed"
            echo "Tests Failed: $tests_failed"
          else
            echo "No test results found."
          fi
