name: iOS Build CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Ruby 3.3.3, CocoaPods 1.16.2, and xcpretty
      run: |
        ruby_version="3.3.3"; cocoapods_version="1.16.2"; \
        brew install ruby@$ruby_version && \
        sudo gem install cocoapods -v $cocoapods_version && \
        sudo gem install xcpretty
      shell: /bin/bash

    - name: Install CocoaPods dependencies
      run: |
        pod install
      working-directory: ./  # Assuming the Podfile is in the root directory

    - name: Build project
      run: |
        xcodebuild -workspace Woloo.xcworkspace -scheme Woloo -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13' build

    - name: Run unit tests (when test cases are available)
      run: |
        xcodebuild -workspace Woloo.xcworkspace -scheme Woloo -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13' test | tee result.log | xcpretty -r junit
      continue-on-error: true

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: junit-report
        path: result.xml
