name: iOS CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.3

    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods
        pod install
      working-directory: ./  # Adjust if necessary

    - name: Install xcpretty
      run: gem install xcpretty

    - name: Set Xcode version
      run: sudo xcode-select -s /Applications/Xcode_14.2.app/Contents/Developer

    - name: Clean project
      run: |
        xcodebuild clean -workspace Woloo.xcworkspace -scheme Woloo -sdk iphonesimulator

    - name: Remove Pods and re-install
      run: |
        rm -rf Pods
        rm -rf Woloo.xcworkspace
        pod install

    - name: Build project
      run: |
        xcodebuild -workspace Woloo.xcworkspace -scheme Woloo -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13' build

    - name: Run unit tests
      run: |
        xcodebuild -workspace Woloo.xcworkspace -scheme Woloo -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13' test | xcpretty -r junit --output result.xml
      continue-on-error: true

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: junit-report
        path: result.xml
