name: iOS Build CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set Xcode version
      run: |
        xcode_version="15.0.1" # Use the exact available version
        sudo xcode-select --switch /Applications/Xcode_$xcode_version.app || exit 1
        xcodebuild -version

    - name: Install Ruby, CocoaPods, and xcpretty
      run: |
        ruby_version="3.2"
        cocoapods_version="1.16.2"
        # Install Ruby
        brew install ruby@$ruby_version || exit 1
        export PATH="/opt/homebrew/opt/ruby@$ruby_version/bin:$PATH"
        # Install CocoaPods
        gem install cocoapods -v $cocoapods_version || exit 1
        # Install xcpretty
        gem install xcpretty || exit 1
        # Verify installations
        ruby -v
        pod --version
        xcpretty --version
        xcodebuild -version
      shell: bash

    - name: Clean CocoaPods cache
      run: pod cache clean --all

    - name: Install CocoaPods dependencies
      run: |
        pod install --verbose || exit 1
      working-directory: ./  # Adjust if necessary

    - name: Build project
      run: |
        xcodebuild -workspace Woloo.xcworkspace -scheme Woloo -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 13' build || exit 1

    - name: Run unit tests
      run: |
        xcodebuild -workspace Woloo.xcworkspace -scheme Woloo -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 13' test | \
          tee result.log | xcpretty -r junit || exit 1

   

