name: iOS CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Xcode
      uses: apple-actions/setup-xcode@v2  # Ensure compatibility with Xcode 14.2
      with:
        xcode-version: '14.2'  # Set to the exact Xcode version

    - name: Set up Ruby (version 3.3.3)
      run: |
        brew install rbenv
        rbenv install 3.3.3
        rbenv global 3.3.3
        ruby -v  # Verify Ruby version

    - name: Install CocoaPods (version 1.16.2)
      run: |
        gem install cocoapods -v 1.16.2
        pod install
      working-directory: Woloo.xcworkspace

    - name: Install xcpretty
      run: |
        gem install xcpretty

    - name: Build project
      run: |
        xcodebuild -workspace Woloo.xcworkspace -scheme Woloo -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13' build

    - name: Run unit tests (when test cases are available)
      run: |
        xcodebuild -workspace Woloo.xcworkspace -scheme Woloo -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13' test | tee result.log | xcpretty -r junit
      continue-on-error: true

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: junit-report
        path: result.xml
