name: iOS CI/CD Pipeline

on:
  push:
    branches:
      - master  # This triggers on any push to the 'dev' branch.

jobs:
  build:
    runs-on: macos-latest  # macOS environment for iOS build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Xcode
      uses: actions/setup-xcode@v3  # Correct action to use for Xcode setup
      with:
        xcode-version: '14.2'  # Ensure correct Xcode version is used

    - name: Install CocoaPods
      run: |
        gem install cocoapods
        pod install  # Install the dependencies via CocoaPods
      working-directory: Woloo.xcworkspace

    - name: Install xcpretty
      run: |
        gem install xcpretty  # For better formatted test output

    - name: Build project
      run: |
        xcodebuild -workspace Woloo.xcworkspace -scheme Woloo -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13' build

    - name: Run unit tests (when test cases are available)
      run: |
        xcodebuild -workspace Woloo.xcworkspace -scheme Woloo -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 13' test | tee result.log | xcpretty -r junit  # Running tests and formatting results
      continue-on-error: true

    - name: Upload test results
      if: always()  # This ensures that the report is uploaded even if the test fails.
      uses: actions/upload-artifact@v3
      with:
        name: junit-report
        path: result.xml  # Path to the test results
