name: iOS Build

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      # Install Pods (no cd ios)
      - name: Install Pods
        run: pod install

      # Build
      - name: Build iOS App
        run: |
          xcodebuild -workspace Woloo.xcworkspace \
          -scheme Woloo \
          -configuration Debug \
          -sdk iphoneos \
          -archivePath $PWD/build/Woloo.xcarchive archive

      # Create plist
      - name: Create ExportOptions.plist
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > ExportOptions.plist
          echo '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN">' >> ExportOptions.plist
          echo '<plist version="1.0"><dict>' >> ExportOptions.plist
          echo '<key>method</key><string>development</string>' >> ExportOptions.plist
          echo '</dict></plist>' >> ExportOptions.plist

      # Export IPA
      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
          -archivePath build/Woloo.xcarchive \
          -exportOptionsPlist ExportOptions.plist \
          -exportPath build

      # Upload
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/*.ipa
