name: iOS Build

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: macos-26

    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # List available Xcode versions
      - name: List Xcode Versions
        run: ls /Applications | grep Xcode

      # Select Xcode
      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode.app

      # Verify Xcode version
      - name: Check Xcode Version
        run: xcodebuild -version

      # List simulators
      - name: List Simulators
        run: xcrun simctl list devices

      # Install pods
      - name: Install Pods
        run: pod install --repo-update

      # Build app
      - name: Build iOS App
        run: |
          xcodebuild -workspace Woloo.xcworkspace \
          -scheme Woloo \
          -configuration Debug \
          -sdk iphonesimulator \
          -destination 'generic/platform=iOS Simulator' \
          ONLY_ACTIVE_ARCH=NO \
          build

      # Upload logs if failed
      - name: Upload Logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ios-build-logs
          path: ~/Library/Logs/DiagnosticReports
